services:
  example-api-db:
    build:
      context: ./example-api
    image: pgvector/pgvector:pg17
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${API_DB_USER} -d ${API_DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${API_DB_PASSWORD?Variable not set}
      - POSTGRES_USER=${API_DB_USER?Variable not set}
      - POSTGRES_DB=${API_DB_NAME?Variable not set}
    volumes:
      - example-api-db-data:/var/lib/postgresql/data
    networks:
      - example-api-network
  example-api-app:
    build:
      context: ./example-api
      dockerfile: Dockerfile
    restart: always
    # This is a problem for new projects and pretty much breaks fastapi and uv's ability to do what it needs to do with files.
    user: ${DOCKER_CURRENT_USER?Variable not set}
    healthcheck:
      test: ["CMD-SHELL", "curl --fail 'http://127.0.0.1:80/api/utils/health-check/' || exit 1"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./example-api/migrations:/app/migrations
      - ./example-api/datasets:/app/datasets
    command: bash /app/scripts/start.sh
    develop:
      watch:
        - action: sync
          path: ./example-api/app
          target: /app/app
        - action: rebuild
          path: ./example-api/pyproject.toml
        - action: rebuild
          path: .env
    depends_on:
      example-api-db:
        condition: service_healthy
        restart: true
    networks:
      - example-api-network
networks:
  example-api-network:
    driver: bridge
volumes:
  example-api-db-data: