"""make imdb id column nullable

Revision ID: 0b7ba1397fd0
Revises: f1ad25bb4571
Create Date: 2025-08-12 21:40:54.598697

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b7ba1397fd0"
down_revision: Union[str, Sequence[str], None] = "f1ad25bb4571"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("films", "imdb_id", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("films", "imdb_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
