"""adding datetimestamps for directors table.

Revision ID: 23565d4f07ae
Revises: c95dbceb5baa
Create Date: 2025-07-29 01:16:06.495307

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23565d4f07ae"
down_revision: Union[str, Sequence[str], None] = "c95dbceb5baa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "filmdirector",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "filmdirector",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("filmdirector", "updated_at")
    op.drop_column("filmdirector", "created_at")
    # ### end Alembic commands ###
