"""adding film director relationship

Revision ID: 36e6efb781ed
Revises: d2f5b4b90fad
Create Date: 2025-07-29 00:32:17.901990

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36e6efb781ed"
down_revision: Union[str, Sequence[str], None] = "d2f5b4b90fad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("film", sa.Column("director_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "film", "filmdirector", ["director_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'film', type_='foreignkey')
    op.drop_column("film", "director_id")
    # ### end Alembic commands ###
