"""create relationship for embeddings and films

Revision ID: 3a4654aa0b3f
Revises: aeecc22b6e09
Create Date: 2025-07-30 12:10:27.219317

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a4654aa0b3f"
down_revision: Union[str, Sequence[str], None] = "aeecc22b6e09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("film", sa.Column("embedding_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "film", "embedding", ["embedding_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, "film", type_="foreignkey")
    op.drop_column("film", "embedding_id")
    # ### end Alembic commands ###
