"""allow meta score to be empty

Revision ID: 54ff0b55dc3f
Revises: 23565d4f07ae
Create Date: 2025-07-29 01:21:16.051777

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54ff0b55dc3f"
down_revision: Union[str, Sequence[str], None] = "23565d4f07ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("film", "meta_score", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("film", "meta_score", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
