"""creating film tables

Revision ID: acce847a2e87
Revises: c8f4bae6a505
Create Date: 2025-07-29 00:13:38.806663

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "acce847a2e87"
down_revision: Union[str, Sequence[str], None] = "c8f4bae6a505"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "film",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("overview", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=False),
        sa.Column("certificate", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("runtime_minutes", sa.Integer(), nullable=False),
        sa.Column("imdb_rating", sa.Float(), nullable=False),
        sa.Column("meta_score", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "filmdirector",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "filmgenre",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("filmgenre")
    op.drop_table("filmdirector")
    op.drop_table("film")
    # ### end Alembic commands ###
