"""removed certificate column

Revision ID: c95dbceb5baa
Revises: 36e6efb781ed
Create Date: 2025-07-29 00:52:03.750044

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c95dbceb5baa'
down_revision: Union[str, Sequence[str], None] = '36e6efb781ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'certificate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('certificate', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
