"""make film table name column unique

Revision ID: d2f5b4b90fad
Revises: acce847a2e87
Create Date: 2025-07-29 00:23:38.127930

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2f5b4b90fad"
down_revision: Union[str, Sequence[str], None] = "acce847a2e87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "film", ["name"])
    op.create_unique_constraint(None, "filmdirector", ["name"])
    op.create_unique_constraint(None, "filmgenre", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("filmgenre_name_key", "filmgenre", type_="unique")
    op.drop_constraint("filmdirector_name_key", "filmdirector", type_="unique")
    op.drop_constraint("film_name_key", "film", type_="unique")
    # ### end Alembic commands ###
